version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
