/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * For more: https://dev.to/nazeelashraf/writing-type-safe-api-clients-in-typescript-1j92
 */


export interface paths {
  "/markets": {
    /** List all markets */
    get: operations["listMarkets"];
  };
  "/markets/{marketId}": {
    /** Info for a specific market */
    get: operations["showMarketById"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Market: {
      id: string;
      name: string;
      base_currency: string;
      quote_currency: string;
      minimum_order_amount: {
        amount: number;
        currency: string;
      };
      taker_fee: number;
      maker_fee: number;
      max_orders_per_minute: number;
      maker_discount_percentage: string;
      taker_discount_percentage: string;
    };
    Markets: components["schemas"]["Market"][];
    OrderBook: {
      asks: [string, string][];
      bids: [string, string][];
    };
    Error: {
      code: number;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List all markets */
  listMarkets: {
    parameters: {};
    responses: {
      /** @description An array of markets */
      200: {
        headers: {
          /** @description A link to the next page of responses */
          "x-next"?: string;
        };
        content: {
          "application/json": components["schemas"]["Markets"];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Info for a specific market */
  showMarketById: {
    parameters: {
      path: {
        /** @description The id of the pet to retrieve */
        marketId: string;
      };
    };
    responses: {
      /** @description Expected response to a valid request */
      200: {
        content: {
          "application/json": components["schemas"]["Markets"];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
